# Site settings
title: "Eslam O. Osman"
email: eom.osman@gmail.com
description: "Personal Website"
baseurl: ""
url: "https://eslam-osman.github.io/"
title_description: "Eslam received his PhD from University of Essex, UK. His research focused on corals in extreme environments to describe corals susceptibility to thermal stress along the Red Sea. He identified genetic variants of endosymbiotic zooxanthellae and the associated microbial community that may describe the tolerance of corals to extreme thermal anomalies along the Red Sea.
During his postdoc at Penn State University, USA, with Prof. Iliana Baums, he investigated the acclimation mechanisms of corals living near methane seeps in the Gulf of Mexico using integrated genomic and ecological approaches."
title_image: "Eslam.jpg"
google_analytics: "UA-20365477-4"
disqus_account: Eslam-Osman
github_repository: https://github.com/Eslam-Osman
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
facebook_link: https://www.facebook.com/eslam.osama.988/
twitter_username: Eslam_O_Osman
github_username:  Eslam-Osman
linkedin_link: https://www.linkedin.com/in/eslam-o-osman-20a20536/
instagram_username: 



# Footer
footer_left: "Eslam O. Osman"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
