# Site settings
title: "Eslam O. Osman"
email: eom.osman@gmial.com
description: "Personal Website"
baseurl: ""
url: "https://eslam-osman.github.io/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "Eslam.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/Eslam-Osman
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: Eslam_O_Osman
github_username:  Eslam-Osman
instagram_username: 
linkedin_link: https://www.linkedin.com/in/eslam-o-osman-20a20536/
facebook_link: https://www.facebook.com/eslam.osama.988/

# Footer
footer_left: "Eslam O. Osman"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
